# Generated by Django 3.2 on 2022-06-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='number',
        ),
    ]
