# Generated by Django 3.2 on 2022-06-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220603_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='complement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(default='', max_length=250),
        ),
    ]
