# Generated by Django 3.2 on 2022-06-03 16:13

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220603_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='postal_code',
            field=localflavor.br.models.BRPostalCodeField(default='', max_length=9, verbose_name='CEP'),
        ),
    ]
