# Generated by Django 3.2 on 2022-06-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shippingaddress_postal_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
