# Generated by Django 3.2 on 2022-06-09 17:47

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220609_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP'),
        ),
    ]
