# Generated by Django 3.2 on 2022-06-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T', 'Terço'), ('L', 'Livro'), ('E', 'Estatua')], max_length=1, null=True),
        ),
    ]
