# Generated by Django 3.2 on 2022-06-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sold',
            field=models.IntegerField(default=1),
        ),
    ]
