# Generated by Django 3.2 on 2022-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orderitem_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sold',
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=1),
        ),
    ]
