# Generated by Django 3.2 on 2022-10-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
