# Generated by Django 3.2 on 2022-10-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221029_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Estado')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=True, verbose_name='Endereço Padrão'),
        ),
    ]
