# Generated by Django 3.2 on 2022-10-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221031_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.state'),
        ),
    ]
